# WhatsApp Credentials

whatsapp.auth =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJjOWYxZTA5Zi1jODRlLTQyNTYtODc1OC02NmY3NDhhM2U3OTUiLCJ1bmlxdWVfbmFtZSI6InBvbGlyYXZpa3VtYXJyZWRkeUBnbWFpbC5jb20iLCJuYW1laWQiOiJwb2xpcmF2aWt1bWFycmVkZHlAZ21haWwuY29tIiwiZW1haWwiOiJwb2xpcmF2aWt1bWFycmVkZHlAZ21haWwuY29tIiwiYXV0aF90aW1lIjoiMDMvMDYvMjAyMyAwOToyMToyNyIsImRiX25hbWUiOiIxMDM4MTMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBRE1JTklTVFJBVE9SIiwiZXhwIjoyNTM0MDIzMDA4MDAsImlzcyI6IkNsYXJlX0FJIiwiYXVkIjoiQ2xhcmVfQUkifQ.a3U3k1B3w3hvOJhqw5NsEwO8BUn_Vtkx7sJ9pz5EUR8
#whatsapp.auth =Basic cG9saXJhdmlrdW1hcnJlZGR5QGdtYWlsLmNvbTpBbGxAbmV0MjAyMQ==
whatsapp.api =https://live-mt-server.wati.io/103813/api/v1
#whatsapp.api =https://app.wati.io/login
whatsapp.api.getMessages = /getMessages/{whatsappNumber}?pageSize={pageSize}&pageNumber={pageNumber}

whatsapp.api.sendSessionMessage = /sendSessionMessage/{whatsappNumber}?messageText={messageText}

whatsapp.template.msg=https://live-mt-server.wati.io/103813/api/v2/sendTemplateMessages

whatsapp.api.sendSessionFile = /sendSessionFile/{whatsappNumber}?caption={caption}

whatsapp.api.button=/sendInteractiveButtonsMessage?whatsappNumber={whatsappNumber}


whatsapp.api.button=/sendInteractiveButtonsMessage?whatsappNumber={whatsappNumber}

# whatsapp button messages text
main.menu.button=MainMenu
previous.menu.button=PreviousMenu
main.menu.button.swahili=MenuKuu
previous.menu.button.swahili=Rudinyuma
whatsapp.api.getMedia = /getMedia?fileName={data}

# common api

whatsapp.save = http://192.168.1.95:9080/whatsApp/send
whatsapp.save.auth = Basic dmlzaW9uOnZpc2lvbkAxMjMj

wa.hit.slash.one=\\

wa.hit.slash.two=\\\\


# WhatsAppApi

wa.webhook = http://192.168.1.95:7373/whatsapp/webhook
wa.webhook.auth = Basic d2hhdHNhcHBhcGk6d2hhdHNhcHBhcGlAMTIzIw==

wa.preins.image.path=/home/ewayportal/commonpath/WhatsappImages/
wa.preins.screen.link=https://digigoalliance.com/CaptureImage/#/Upload?e={TranId}
# timezone

timezone.hours = 0
timezone.minutes = -10

# messageStart

start.message = hi



# paths

#common.file.path = E:/ClusterStorage/Volume1/Motor/uat/

common.file.path = /home/ewayportal/commonpath/WhatsappImages/

#smb://DESKTOP-CBSM6O1;MSTSPL:admin@192.168.1.25/Shanmugam/
claim.whatsapp.login.url=http://192.168.1.42:5050/authentication/login
claim.whatsapp.document.url=http://192.168.1.42:6050/whatsappupload

#claim intimation api's======================================================###===================================
get.policy.details.bypolicyno=https://apps.alliance.co.tz/ClaimApi/api/get/policyDetails
get.policy.details.bychassisNo=https://apps.alliance.co.tz/ClaimApi/api/get/policydetailsbyregno
get.loss.type=https://apps.alliance.co.tz/ClaimApi/api/claimlosstype
get.cause.of.loss=https://apps.alliance.co.tz/ClaimApi/api/causeoflossdropdown
claim.intimation=https://apps.alliance.co.tz/ClaimApi/api/simple/claimintimationdetails
token.api=https://apps.alliance.co.tz/ClaimApi/authentication/login
claim.status.bychassis=https://apps.alliance.co.tz/ClaimApi/api/getallclaimintimationdetailsuserside
claim.status.bypolicy=https://apps.alliance.co.tz/ClaimApi/api/getallclaimintimationdetailsbypolicyno
get.claim.details=https://apps.alliance.co.tz/ClaimApi/api/viewclaimdetails/{CLAIM_NO}
get.claim.status =https://apps.alliance.co.tz/ClaimApi/api/claim-status-tracking

InsuranceId=100019
LoginType=user
Password=Admin@01
UserId=guest

#===========EwayPortal Create Quote Api's============================================================================================================

eway.motor.tira.api=https://apps.alliance.co.tz/EwayMotorApiLive/regulatory/showvehicleinfo
eway.motor.save.api=https://apps.alliance.co.tz/EwayMotorApiLive/api/savemotordetails
eway.motor.calc.api=https://apps.alliance.co.tz/EwayCommonApiLive/calculator/calc
eway.motor.view.calc.api=https://apps.alliance.co.tz/EwayCommonApiLive/api/view/calc
eway.motor.vehicle.update.api=https://apps.alliance.co.tz/EwayAdminApiLive/eway/embedded/get/whatsapp/vehicle
eway.motor.policy.holder.api=https://apps.alliance.co.tz/EwayMotorApiLive/regulatory/showpolicyholder
eway.motor.section.api=https://apps.alliance.co.tz/EwayAdminApiLive/master/dropdown/productsection
eway.motor.usage.api=https://apps.alliance.co.tz/EwayCommonApiLive/api/dropdown/vehicleusage
eway.motor.customer.api=https://apps.alliance.co.tz/EwayCommonApiLive/api/customer
eway.motor.buypolicy=https://apps.alliance.co.tz/EwayCommonApiLive/quote/buypolicy
eway.motor.makepayment=https://apps.alliance.co.tz/EwayCommonApiLive/payment/makepayment
eway.motor.insertpayment =https://apps.alliance.co.tz/EwayCommonApiLive/payment/insertpaymentdetails
eway.motor.createlogin=https://apps.alliance.co.tz/EwayCommonApiLive/otp/createLogin
eway.claimDetails.api=https://apps.alliance.co.tz/EwayCommonApiLive/embedded/getClaimDetails
eway.token.api=https://apps.alliance.co.tz/EwayCommonApiLive/authentication/login
eway.motor.paymentlink=https://digigoalliance.com/WhatsAppApiMeta/insurance/buypolicy/
eway.motor.selcom.payementApi=https://apps.alliance.co.tz/EwayCommonApiLive/selcom/v1/checkout/create-order-minim/
eway.motor.selcom.paymentCheckApi=https://apps.alliance.co.tz/EwayCommonApiLive/selcom/v1/checkout/order-status/
eway.motor.policy.document=https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/embedded/create/policy/schedule/
eway.motor.redirect.url=https://api.whatsapp.com/send/?phone=255743000301&TEXT&TYPE=phone_number&app_absent=0
tira.post.api=https://apps.alliance.co.tz/EwayCommonApiLive/payment/pushtira
turl.api =https://digigoalliance.com/turl/getTUrl

#======================================EWAY MASTER API FOR WHATSAPP FLOWS=====================
wh.policyholder.api=https://apps.alliance.co.tz/EwayCommonApiLive/dropdown/policyholderidtype
wh.section.api=https://apps.alliance.co.tz/EwayAdminApiLive/master/dropdown/productsection
wh.bodytype.api=https://apps.alliance.co.tz/EwayCommonApiLive/master/dropdown/bodytype
wh.vehicleusage.api=https://apps.alliance.co.tz/EwayCommonApiLive/api/dropdown/vehicleusage
wh.eway.token.api=https://apps.alliance.co.tz/EwayCommonApiLive/authentication/login

wh.customer.title.api=https://apps.alliance.co.tz/EwayCommonApiLive/dropdown/title
wh.customer.occpation.api=https://apps.alliance.co.tz/EwayCommonApiLive/master/dropdown/occupation
wh.customer.countryCode.api=https://apps.alliance.co.tz/EwayCommonApiLive/dropdown/mobilecodes
wh.customer.country.api=https://apps.alliance.co.tz/EwayCommonApiLive/master/dropdown/country
wh.customer.gender.api=https://apps.alliance.co.tz/EwayCommonApiLive/dropdown/policyholdergender

wh.vehcile.color.api=https://apps.alliance.co.tz/EwayCommonApiLive/master/dropdown/color
wh.vehicle.fuelUsed.api=https://apps.alliance.co.tz/EwayCommonApiLive/dropdown/fueltype
wh.vehicle.motorCategory.api=https://apps.alliance.co.tz/EwayCommonApiLive/dropdown/motorcategory
wh.stp.vehicleUsage.api=https://apps.alliance.co.tz/EwayCommonApiLive/api/dropdown/induvidual/vehicleusage
wh.stp.bodyType.api=https://apps.alliance.co.tz/EwayCommonApiLive/master/dropdown/induvidual/bodytype
wh.stp.make=https://apps.alliance.co.tz/EwayCommonApiLive/master/dropdown/motormake
wh.stp.model=https://apps.alliance.co.tz/EwayCommonApiLive/master/dropdown/motormakemodel
wh.stp.region=https://apps.alliance.co.tz/EwayCommonApiLive/master/dropdown/region
wh.cq.policytype=https://apps.alliance.co.tz/EwayAdminApiLive/master/dropdown/policytype
wh.stp.getallmotordetails =https://apps.alliance.co.tz/EwayMotorApiLive/api/getallmotordetails
wh.get.ewaydata.api=https://apps.alliance.co.tz/EwayMotorApiLive/api/validations
wh.get.reg_no.api=https://apps.alliance.co.tz/EwayMotorApiLive/regulatory/showvehicleinfo
wh.save.vehicle.info.api=https://apps.alliance.co.tz/EwayMotorApiLive/regulatory/savevehicleinfo
wh.save.motor.details.api=https://apps.alliance.co.tz/EwayMotorApiLive/api/savemotordetails
wh.get.insurance.type.api=https://apps.alliance.co.tz/EwayAdminApiLive/master/dropdown/productsection
wh.get.motor.details=https://apps.alliance.co.tz/EwayMotorApiLive/api/getmotordetails
wh.get.insurance.type=https://apps.alliance.co.tz/EwayAdminApiLive/master/dropdown/productsection
wh.get.reg.no=https://apps.alliance.co.tz/EwayMotorApiLive/regulatory/showvehicleinfo
wh.get.policy.body.type=https://apps.alliance.co.tz/EwayCommonApiLive/master/dropdown/bodytype
wh.get.policy.vehicle.usage=https://apps.alliance.co.tz/EwayCommonApiLive/api/dropdown/vehicleusage
wh.push.mail.tocustomer=https://apps.alliance.co.tz/EwayCommonApiLive/post/notification/pushnotification

#==========================================================================

meta.message.api =https://graph.facebook.com/v18.0/448049831720158/messages
meta.message.api.auth=Bearer EAAcwlQVWEbsBO3JRlEjA9bfZA1UYsWCs2MziEUTWpJGZB7AMZBCa4WZBiDmJMHdQ1jv0pV0rsZBhVcBcbR8TOtc4wvJBLFMVZBzTqMcj707Wc1xvVjV52vgUTQqUIlPLst7f8z8UUBP6VPqhQZCSEl72jVp9r8Yx9OrAGfzRR1bHwCrGH4OCG2DdnkgJfnZCpZAA28gZDZD
meta.get.image.api=https://graph.facebook.com/v19.0/{IMAGE_ID}
meta.image.store.path=/home/ewayportal/commonpath/WhatsappImages/
# FOR lOCAL
metaSecurityKeyFilePath=C:\\Users\\LENOVO\\Desktop\\MetaPemFile\\privatenew.pem




# FOR LIVE & UAT
#metaSecurityKeyFilePath=/home/ewayportal/commonpath/privatenew.pem


#=========================================================================================
# Image validation check api's
python.image.token.api=https://mysite-ah8i.onrender.com/api/V1/auth/login
python.image.validate.api=https://mysite-ah8i.onrender.com/api/V1/image_parser/detect-features
python.image.token.username=mspl
python.image.token.password=mspl


#=================Phoenix Details=========================================================
wh.phoenix.token.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/authentication/login
wh.phoenix.customer.title.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/dropdown/title
wh.phoenix.customer.region =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/master/dropdown/region
wh.phoenix.customer.gender =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/dropdown/policyholdergender
wh.phoenix.customer.occupation =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/master/dropdown/occupation
wh.phoenix.customer.idtype =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/dropdown/policyholderidtype
wh.phoenix.stp.vehicleUsage.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/api/dropdown/induvidual/vehicleusage
wh.phoenix.stp.bodytype.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/master/dropdown/induvidual/bodytype
wh.phoenix.stp.motorcategory.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/dropdown/motorcategory
wh.phoenix.stp.vehiclecolor.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/master/dropdown/color
wh.phoenix.customer.district =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/master/dropdown/regionstate
wh.get.phoenix.validation.api =http://192.168.1.42:8084/api/validations
wh.get.phoenix.insuranceclass.api =http://192.168.1.42:8084/master/dropdown/policytype
wh.get.phoenix.insuranceperiod.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/dropdown/quoteperiod   
wh.phoenix.stp.motormake.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/master/dropdown/motormake
wh.phoenix.stp.motormodel.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/master/dropdown/motormakemodel
wh.phoenix.noclaim.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/master/getbyitemvalue
wh.phoenix.savevehicleinfo.api =https://wecoreuat.wecorephoenixgroup.com/EwayMotorApi/regulatory/savevehicleinfo
wh.phoenix.savemotordetails.api =https://wecoreuat.wecorephoenixgroup.com/EwayMotorApi/api/savemotordetails
wh.phoenix.customersave.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/api/savecustomerdetails
wh.phoenix.showvehicleinfo.api =https://wecoreuat.wecorephoenixgroup.com/EwayMotorApi/regulatory/showvehicleinfo        
wh.phoenix.buypolicy.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/quote/buypolicy          
wh.phoenix.calc.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/calculator/calc
wh.phoenix.view.calc.api=https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/api/view/calc
wh.phoenix.logincreation.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/otp/createLogin
wh.phoenix.makepayment.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/payment/makepayment
wh.phoenix.insertpayment.api =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/payment/insertpaymentdetails
phoenix.swaziland.motor.thirdparty.payementApi =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/selcom/v1/checkout/create-order/
phoenix.mozambique.motor.thirdparty.payementApi =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/selcom/v1/checkout/create-order/
phoenix.namibia.motor.thirdparty.payementApi =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/selcom/v1/checkout/create-order/
phoenix.boatawana.motor.thirdparty.payementApi =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/selcom/v1/checkout/create-order/
phoenix.zambia.motor.thirdparty.payementApi =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/selcom/v1/checkout/create-order/
phoenix.swaziland.motor.thirdparty.paymentCheckApi =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/selcom/v1/checkout/order-status/
phoenix.mozambique.motor.thirdparty.paymentCheckApi =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/selcom/v1/checkout/order-status/
phoenix.namibia.motor.thirdparty.paymentCheckApi =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/selcom/v1/checkout/order-status/
phoenix.boatawana.motor.thirdparty.paymentCheckApi =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/selcom/v1/checkout/order-status/
phoenix.zambia.motor.thirdparty.paymentCheckApi =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/selcom/v1/checkout/order-status/
phoenix.motor.policy.document =https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/embedded/create/policy/schedule/
phoenix.tira.post.api =
phoenix.motor.swaziland.redirect.url=https://api.whatsapp.com/send/?phone=26879926003&TEXT&TYPE=phone_number&app_absent=0
phoenix.motor.mozambique.redirect.url=https://api.whatsapp.com/send/?phone=255743000301&TEXT&TYPE=phone_number&app_absent=0
phoenix.motor.namibia.redirect.url=https://api.whatsapp.com/send/?phone=255743000301&TEXT&TYPE=phone_number&app_absent=0
phoenix.motor.boatawana.redirect.url=https://api.whatsapp.com/send/?phone=255743000301&TEXT&TYPE=phone_number&app_absent=0
phoenix.motor.zambia.redirect.url=https://api.whatsapp.com/send/?phone=255743000301&TEXT&TYPE=phone_number&app_absent=0
phoenix.motor.payment.link =https://online.phoenixbotswana.com/WhatsAppApiMeta/insurance/phoenix/buypolicy/
wh.phoenix.getallmotordetails =https://wecoreuat.wecorephoenixgroup.com/EwayMotorApi/api/getallmotordetails
wh.phoenix.getmasterids.api=https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/master/getid
askeva.template.api=https://backend.askeva.io/v1/message/send-message?token=ec7ac3c2327e2d3187ae10cc9277df4ec8ca275ee7bbf378b6afc47380db173cb14ea9b8b19b5077be53fe0c425c8df6ff724e27edfd8638f0a4ca8ac5c513a5
askeva.template.api.zambia=https://backend.askeva.io/v1/message/send-message?token=b503691f4f18671d8de72d27c64cdb358fd241bd0045d8d12b80ff0ee8ff90a759659313ce65e2620bca38dc6d843d0d508e2f524bec928a0329964f32c578d4
wh.phoenix.getcustomer.api=https://wecoreuat.wecorephoenixgroup.com/EwayCommonApi/api/getcustomerdetails

zambia.message.api =https://graph.facebook.com/v21.0/535846802950898/messages
zambia.message.auth=Bearer EAA3jxxHtnxMBO1EXngSFTNWlUfX5HdolgYzeuvrvbV5xR1j84uZCJL7tKwFyeG0nFwGBDZBSXk7dsQmQ5ZATzaRuAtojoGiD8S8rwGd2a4SKZBqO41jHRGSp3j0jYyWZAkolrETEp19DgSd8SHfkBabiEOjfCZBuLWFBXFpiQY4oJU44OOZCzR6WBeZC0hCiZCDbyQwZDZD

namibia.message.api =https://graph.facebook.com/v21.0/581380625054001/messages
nambia.message.auth =Bearer EAAcwlQVWEbsBO3JRlEjA9bfZA1UYsWCs2MziEUTWpJGZB7AMZBCa4WZBiDmJMHdQ1jv0pV0rsZBhVcBcbR8TOtc4wvJBLFMVZBzTqMcj707Wc1xvVjV52vgUTQqUIlPLst7f8z8UUBP6VPqhQZCSEl72jVp9r8Yx9OrAGfzRR1bHwCrGH4OCG2DdnkgJfnZCpZAA28gZDZD

mozambique.message.api =
mozambique.message.auth =

boatswana.message.api =https://graph.facebook.com/v21.0/733664026505083/messages
boatswana.message.auth =Bearer EAASraEs2IkABPtAgy73lHxr9TKZBZAKTZC84DcVPG3qdyUZC9vE503MkzjIblW80nyQ4HcZCsnKz0jZCo0iIuXMcSwZC2WTRd8rW9kZB7VHQf2iZAqawJEZCQ2FVZBi5iYlYWavO5UJ1CZAu24bXt4W0lsxM53wGiJDZAjKCECKNr2bbZC8QGXBBZBFAtl1nvi93T1KEQZDZD

swaziland.message.api =
swaziland.message.auth =

external.gemini.api.key =AIzaSyAfiTETtQUDSup9m6ljipzxTxgXLotfXz4 